### ISSUE TITLE
Typings not installing.

### ISSUE THREAD

**Issue by ghost** [chandermani/angular2byexample#11]
I get a whole page of TS2304 errors. I followed these instructions on your readme:

--------------------
If you see a bunch of TypeScript compilation errors while running gulp play, the required typings did not get installed. While npm install should also install the typings, at times this does not happen. To fix this, try to install typings again with command npm run typings install. If the typing installation throws error try to upgrade the typing global installation with command npm install typings -g and then run the command npm run typings install again.
---------------------

This did not change anything. Your help would be appreciated.

Thanks,
Jerry

**Comment by chandermani** [comment]
Hi Jerry, sorry for the late response. Which branch were you trying?

**Comment by front-thinking** [comment]
Hi，@chandermani  . I got the same error. Here is the step:
--------------- problem---------
branch base。
after :npm i -g gulp typings
npm install
gulp play
and than got a lot of TS2304 errors.

----------------answer---------
I search the problem ,finde the same problem [here](https://github.com/angular/quickstart/issues/63).

tried some of the answers, and this one worked. Here is the answer for me, u can have a try, @grayskwrl149 .

add the following to the start of my main.ts in order for it to work properly:

`///<reference path="../node_modules/typescript/lib/lib.es6.d.ts"/> `

hope it work for u.

**Comment by edxxgardo** [comment]
Same problem here. Where is that main.ts file in the project? It is not there. I cannot believe that I spent 2hs jus trying to solve this issue without success. I tried even some of the suggestions in the link mentioned above, and nothing. I hate this never ending story of dependencies and dependencies and dependencies. The more we evolve with software the complicated it becomes.

In my mac I cannot make it work. Any help, please?

**Comment by front-thinking** [comment]
try 'npm install typings -g '  and than 'typing install', there will be a folder typings under trainer, in the typings folder u will see the main.ts. Hope it will work. @edxxgardo

**Comment by edxxgardo** [comment]
@front-thinking It does. Awesome. Thx a bunch buddy ;)

**Comment by chandermani** [comment]
The new way of using typings is going to be using npm packages and no other tools. See here https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

I am going to fix the code to use npm based type reference soon. Meanwhile use this mechanism pointed out by @front-thinking. 
This method 
`npm run typings install` 
currently does not work as npm run is still using the old typings tool.
But this method works fine (as explained by @front-thinking) 
`typings install`

**Comment by chandermani** [comment]
I have just pushed changes that will use _typings_ from npm packages. This should fix the issue.

Remember to upgrade your typescript compiler.

**Comment by edxxgardo** [comment]
That is great. The book is really good, learning a lot!
