### ISSUE TITLE
Page:73 Trainer-workout model textual mismatch

### ISSUE THREAD

**Issue by seydakucuk** [chandermani/angular2byexample#12]
Hello, I am currently reading "Angular 2 by Example" and firstly want to thank you for the great content and samples.
I only want to write about a little mismatch I've noticed on page 73:
"For the workout, we need to track the following properties:
• The name. This should be unique.
• The title. This is shown to the user.
• The exercises that are part of the workout.
• The duration for each exercise.
• The rest duration between two exercises"
"The duration for each exercise" is a property of "ExercisePlan" and doesn't match the properties of "Workout" class. I guess it should rather be "The description of the workout".
This mismatch is not a big deal but I thought you might want to consider if you are planning to release a new edition of the book.
Best regards,

**Comment by chandermani** [comment]
Thanks @seydakucuk, i will make a note of this.
