### ISSUE TITLE
Search not working in the Master Branch

### ISSUE THREAD

**Issue by DanAtCID** [chandermani/angular2byexample#16]
Thank you for writing an excellent book.  I believe that start.html is not complete because the search does not work.

1. When I type in the search term the list of workouts is removed.  
2. When I hit enter nothing happens. (See attachment).
3. When I delete the search term the list appears again.

![workoutsdisappear](https://user-images.githubusercontent.com/23140370/34685706-428c4f5a-f477-11e7-931a-1580127e0955.png)

Here is the content of start.html that I downloaded (see bolded text below):

[start.txt](https://github.com/chandermani/angular2byexample/files/1612618/start.txt)

**Comment by DanAtCID** [comment]
Updated original with start.txt as start.html.

**Comment by kmhennessy** [comment]
Hi Dan,

I don’t know if this is still an issue for you since you closed it. But the search you are referring to is a very basic one that only works with an exact match on the name of the workout. I just tried it myself and it is working.

Regards,
Kevin Hennessy

**Comment by DanAtCID** [comment]
Awesome tip.  It works for me too!  Thanks!
